# Generated by Django 4.1.1 on 2023-12-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="code",
            field=models.CharField(
                default="NONE", max_length=5, verbose_name="код проекта"
            ),
            preserve_default=False,
        ),
    ]
