# Generated by Django 4.1.1 on 2023-04-07 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_taskstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskstatus",
            name="task",
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="tasks.taskstatus",
                verbose_name="статус",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="taskstatus",
            name="status",
            field=models.CharField(max_length=50, verbose_name="Статус задачи"),
        ),
    ]
