# Generated by Django 4.1.1 on 2023-04-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_taskstatus_task_task_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskstatus",
            old_name="status",
            new_name="title",
        ),
    ]
