# Generated by Django 4.1.1 on 2023-04-07 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0004_rename_status_taskstatus_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskstatus",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="когда создан",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskstatus",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_statuses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="кем создан",
            ),
            preserve_default=False,
        ),
    ]
